### ISSUE TITLE
Auto attacking mobs when OnlyKeys is active

### ISSUE THREAD

**Issue by mimuki** [jaszlo/OnlyKeys#2]
looking at any mob (regardless of how you move the camera) will cause the player to damage it repeatedly, as if you were clicking a mouse as fast as you could. this occurs even when the only mods are onlykeys + its dependencies, and stops when you disable it with the hotkey (or remove the mod, of course). 

observed on minecraft version 1.20.1, but I haven't tested other versions

**Comment by jaszlo** [comment]
Has been fixed [here](https://github.com/jaszlo/OnlyKeys/commit/950a9463efcb4bd5920f94d7cbcf15cccebbeda4). Working on releasing an update. This is a quick solution. This will prevent the game from crashing but also you might lose the behaviour where you select the last selected slot from the same inventory screens.

**Comment by jaszlo** [comment]
https://modrinth.com/mod/onlykeys/versions
