### ISSUE TITLE
Crash when opening chests in a certain order

### ISSUE THREAD

**Issue by mimuki** [jaszlo/OnlyKeys#3]
### Steps to reproduce:

1. open a double chest, and select any item in your inventory or hotbar
2. open a single chest

Seemingly OnlyKeys is trying to select the same inventory slot (by number), but because that number doesn't exist in the smaller container, it crashes.

Observed on 1.20.1

**Comment by jaszlo** [comment]
Fixd it [here](https://github.com/jaszlo/OnlyKeys/commit/89b81a502fedc255d881cc24fa089715f3ee366c). 

Now the behaviour is not optimal, as when the slot-id is too high it just selects 0. Will probably fix this better in the future but for know this should be enough.

**Comment by jaszlo** [comment]
Release was published on [Modrinth](https://modrinth.com/mod/onlykeys/versions)
